### ISSUE TITLE
Suggested additions to the README

### ISSUE THREAD

**Issue by beep** [shaunagm/turn-the-tables#1]
Hi! This is a _fantastic_ initiative — I’m so glad y’all are doing this.

I have a couple suggestions for the README, if they’d be at all welcome! Please use what you think is relevant, and ignore everything else!

- I wonder if the OPEIU mention could/should link to OPEIU’s [Tech Workers Local Union 1010](https://www.techworkersunion-1010.org/) instead?
- Under *Organizations Supporting Tech Workers*, what about including [Emergency Workplace Organizing (EWOC)](https://workerorganizing.org/) and/or [Organizing for Power](https://www.rosalux.de/en/o4p)? (They’re not tech worker-specific, mind, but I think their work still very much applies.)
- Under *Employer-Specific Organizations*, a couple other names:
  - [Nava United](https://www.navaunited.org/)
  - [NYT Tech Guild](https://nytimesguild.org/tech/)
  - [CfA Workers United](https://cfaworkersunited.com/)
  - There are two unions at ActBlue: [ActBlue Union](https://twitter.com/actblueunion), and [ActBlue Tech Workers Union](https://abtwu.org/).
  - [IAM Tempus AI Workers](https://www.goiam.org/news/tempus-ai-workers-in-chicago-vote-to-join-iam-union/)

Thank you again for starting this work!

**Comment by shaunagm** [comment]
Thank you so much @beep! I've incorporated your suggestions in #2
